agendaMedica/config/routes.rb
AgendaMedica::Application.routes.draw do
  resources :medicos

  resources :convenios

  resources :pacientes

  resources :agendamentos

  get "home/index"









  root :to => 'home#index'


end

agendaMedica/app/models/agendamento.rb
class Agendamento < ActiveRecord::Base
  attr_accessible :cancelado, :concluido, :data, :hora, :id, :id_convenio, :id_medico, :id_paciente, :prescricao, :tempoconsulta  
  validates :data, :hora, :id, :id_convenio, :id_medico, :id_paciente, :prescricao, :tempoconsulta, :presence => true   
  validates :id, :numericality => { :only_integer => true }
  validates :id, :uniqueness => { :message => "Campo ID  unico" }  
  validates :prescricao, :length => { :maximum => 250, :message => "nome e no maximo 250 caracteres"}     
  
end

agendaMedica/app/controllers/agendamentos_controller.rb
class AgendamentosController < ApplicationController
  # GET /agendamentos
  # GET /agendamentos.json
  def index
    @agendamentos = Agendamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agendamentos }
    end
  end

  # GET /agendamentos/1
  # GET /agendamentos/1.json
  def show
    @agendamento = Agendamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agendamento }
    end
  end

  # GET /agendamentos/new
  # GET /agendamentos/new.json
  def new
    @agendamento = Agendamento.new

	
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agendamento }
    end
	
  end

  # GET /agendamentos/1/edit
  def edit
    @agendamento = Agendamento.find(params[:id])
  end

  # POST /agendamentos
  # POST /agendamentos.json
  def create
    @agendamento = Agendamento.new(params[:agendamento])        
			
    #@resultado = Agendamento.where("where data = :data and hora >= :hora and hora <= addtime(:hora, tempoconsulta) and id_medico = :id_medico and id_paciente <> :id_paciente",
	#	[params[:data], params[:hora], params[:hora], params[:id_medico], params[:id_paciente]]);
   		
    respond_to do |format|
      
     # unless @resultado
     #  raise "erro ao salvar"
     #  redirect_to :action => 'agendamento_duplicado',  notice: 'Ja existe outro agendamento no mesmo horario.'
     #  flash.now[:error] = "Ja existe outro agendamento no mesmo horario"
     #  render :action => "new"         
     #  return
     # end;
      
      if @agendamento.save
        format.html { redirect_to @agendamento, notice: 'Agendamento was successfully created.' }
        format.json { render json: @agendamento, status: :created, location: @agendamento }
      else
        format.html { render action: "new" }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agendamentos/1
  # PUT /agendamentos/1.json
  def update
    @agendamento = Agendamento.find(params[:id])

    respond_to do |format|
      if @agendamento.update_attributes(params[:agendamento])
        format.html { redirect_to @agendamento, notice: 'Agendamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendamentos/1
  # DELETE /agendamentos/1.json
  def destroy
    @agendamento = Agendamento.find(params[:id])
    @agendamento.destroy

    respond_to do |format|
      format.html { redirect_to agendamentos_url }
      format.json { head :no_content }
    end
  end
end

agendaMedica/app/helpers/agendamentos_helper.rb
module AgendamentosHelper
end

agendaMedica/app/views/agendamentos/_form.html.erb
<%= form_for(@agendamento) do |f| %>
  <% if @agendamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agendamento.errors.count, "error") %> prohibited this agendamento from being saved:</h2>

      <ul>
      <% @agendamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    
  
  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :hora %><br />
    <%= f.time_select :hora %>
  </div>
  <div class="field">
    <%= f.label :tempoconsulta %><br />
    <%= f.number_field :tempoconsulta %>
  </div>
  <div class="field">
    <%= f.label :id_paciente %><br />
    <%= f.collection_select(:id_paciente, Paciente.all, :id, :nome) %>  
  </div>
  <div class="field">
    <%= f.label :id_medico %><br />
    <%= f.collection_select(:id_medico, Medico.all, :id, :nome) %>  
  </div>
  <div class="field">
    <%= f.label :id_convenio %><br />
    <%= f.collection_select(:id_convenio, Convenio.all, :id, :nome) %> 
  </div>
  <div class="field">
    <%= f.label :concluido %><br />
    <%= f.check_box :concluido %>
  </div>
  <div class="field">
    <%= f.label :cancelado %><br />
    <%= f.check_box :cancelado %>
  </div>
  <div class="field">
    <%= f.label :prescricao %><br />
    <%= f.text_area :prescricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

agendaMedica/app/views/agendamentos/edit.html.erb
<h1>Editing agendamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @agendamento %> |
<%= link_to 'Back', agendamentos_path %>

agendaMedica/app/views/agendamentos/index.html.erb
<h1>Listing agendamentos</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Data</th>
    <th>Hora</th>
    <th>Tempoconsulta</th>
    <th>Id paciente</th>
    <th>Id medico</th>
    <th>Id convenio</th>
    <th>Concluido</th>
    <th>Cancelado</th>
    <th>Prescricao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @agendamentos.each do |agendamento| %>
  <tr>
    <td><%= agendamento.id %></td>
    <td><%= agendamento.data %></td>
    <td><%= agendamento.hora %></td>
    <td><%= agendamento.tempoconsulta %></td>
    <td><%= agendamento.id_paciente %></td>
    <td><%= agendamento.id_medico %></td>
    <td><%= agendamento.id_convenio %></td>
    <td><%= agendamento.concluido %></td>
    <td><%= agendamento.cancelado %></td>
    <td><%= agendamento.prescricao %></td>
    <td><%= link_to 'Show', agendamento %></td>
    <td><%= link_to 'Edit', edit_agendamento_path(agendamento) %></td>
    <td><%= link_to 'Destroy', agendamento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Agendamento', new_agendamento_path %>

agendaMedica/app/views/agendamentos/new.html.erb
<h1>New agendamento</h1>
<% if @agendamento.errors.any? %>
	<h2>Erros:</h2>
	<ul>
		<% @agendamento.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
		<% end %>r
	</ul>
<% end %>
<%= render 'form' %>

<%= link_to 'Back', agendamentos_path %>

agendaMedica/app/views/agendamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @agendamento.id %>
</p>

<p>
  <b>Data:</b>
  <%= @agendamento.data %>
</p>

<p>
  <b>Hora:</b>
  <%= @agendamento.hora %>
</p>

<p>
  <b>Tempoconsulta:</b>
  <%= @agendamento.tempoconsulta %>
</p>

<p>
  <b>Id paciente:</b>
  <%= @agendamento.id_paciente %>
</p>

<p>
  <b>Id medico:</b>
  <%= @agendamento.id_medico %>
</p>

<p>
  <b>Id convenio:</b>
  <%= @agendamento.id_convenio %>
</p>

<p>
  <b>Concluido:</b>
  <%= @agendamento.concluido %>
</p>

<p>
  <b>Cancelado:</b>
  <%= @agendamento.cancelado %>
</p>

<p>
  <b>Prescricao:</b>
  <%= @agendamento.prescricao %>
</p>


<%= link_to 'Edit', edit_agendamento_path(@agendamento) %> |
<%= link_to 'Back', agendamentos_path %>