agendaMedica/config/routes.rb
AgendaMedica::Application.routes.draw do
  resources :medicos

  resources :convenios

  resources :pacientes

  resources :agendamentos

  get "home/index"









  root :to => 'home#index'


end

agendaMedica/app/models/medico.rb
class Medico < ActiveRecord::Base
  attr_accessible :crm, :id, :nome  
  validates :crm, :id, :nome, :presence => true 
  validates :id, :numericality => { :only_integer => true }
  validates :id, :uniqueness => { :message => "Campo ID  unico" }
  validates :crm, :uniqueness => { :message => "Campo CRM e unico" }
  validates :nome, :length => { :maximum => 100, :message => "nome e no maximo 100 caracteres"} 
  validates :crm, :length => { :maximum => 20, :message => "CRM e no maximo 20 caracteres" }
end

agendaMedica/app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  # GET /medicos
  # GET /medicos.json
  def index
    @medicos = Medico.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medicos }
    end
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
    @medico = Medico.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medico }
    end
  end

  # GET /medicos/new
  # GET /medicos/new.json
  def new
    @medico = Medico.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medico }
    end
  end

  # GET /medicos/1/edit
  def edit
    @medico = Medico.find(params[:id])
  end

  # POST /medicos
  # POST /medicos.json
  def create
    @medico = Medico.new(params[:medico])

    respond_to do |format|
      if @medico.save
        format.html { redirect_to @medico, notice: 'Medico was successfully created.' }
        format.json { render json: @medico, status: :created, location: @medico }
      else
        format.html { render action: "new" }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /medicos/1
  # PUT /medicos/1.json
  def update
    @medico = Medico.find(params[:id])

    respond_to do |format|
      if @medico.update_attributes(params[:medico])
        format.html { redirect_to @medico, notice: 'Medico was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    @medico = Medico.find(params[:id])
    @medico.destroy

    respond_to do |format|
      format.html { redirect_to medicos_url }
      format.json { head :no_content }
    end
  end
end

agendaMedica/app/helpers/medicos_helper.rb
module MedicosHelper
end

agendaMedica/app/views/medicos/_form.html.erb
<%= form_for(@medico) do |f| %>
  <% if @medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
      <% @medico.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :crm %><br />
    <%= f.text_field :crm %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

agendaMedica/app/views/medicos/edit.html.erb
<h1>Editing medico</h1>

<%= render 'form' %>

<%= link_to 'Show', @medico %> |
<%= link_to 'Back', medicos_path %>

agendaMedica/app/views/medicos/index.html.erb
<h1>Listing medicos</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th>Crm</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @medicos.each do |medico| %>
  <tr>
    <td><%= medico.id %></td>
    <td><%= medico.nome %></td>
    <td><%= medico.crm %></td>
    <td><%= link_to 'Show', medico %></td>
    <td><%= link_to 'Edit', edit_medico_path(medico) %></td>
    <td><%= link_to 'Destroy', medico, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medico', new_medico_path %>

agendaMedica/app/views/medicos/new.html.erb
<h1>New medico</h1>

<% if @medico.errors.any? %>
	<h2>Erros:</h2>
	<ul>
		<% @medico.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
		<% end %>r
	</ul>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', medicos_path %>

agendaMedica/app/views/medicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @medico.id %>
</p>

<p>
  <b>Nome:</b>
  <%= @medico.nome %>
</p>

<p>
  <b>Crm:</b>
  <%= @medico.crm %>
</p>


<%= link_to 'Edit', edit_medico_path(@medico) %> |
<%= link_to 'Back', medicos_path %>