agendaMedica/config/routes.rb
AgendaMedica::Application.routes.draw do
  resources :medicos

  resources :convenios

  resources :pacientes

  resources :agendamentos

  get "home/index"









  root :to => 'home#index'


end

agendaMedica/app/models/paciente.rb
class Paciente < ActiveRecord::Base
  attr_accessible :endereco, :id, :idade, :nome, :rg
  
  validates :id, :uniqueness => { :message => "Campo ID  unico" }  
  validates :rg, :uniqueness => { :message => "Campo RG  unico" }  
  validates :endereco, :id, :nome, :presence => true 
  validates :id, :numericality => { :only_integer => true }    
  validates :nome, :length => { :maximum => 100, :message => "nome e no maximo 100 caracteres"} 
  validates :rg, :length => { :maximum => 10, :message => "RG e no maximo 10 caracteres" }  
end

agendaMedica/app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pacientes }
    end
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
    @paciente = Paciente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paciente }
    end
  end

  # GET /pacientes/new
  # GET /pacientes/new.json
  def new
    @paciente = Paciente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paciente }
    end
  end

  # GET /pacientes/1/edit
  def edit
    @paciente = Paciente.find(params[:id])
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(params[:paciente])

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente was successfully created.' }
        format.json { render json: @paciente, status: :created, location: @paciente }
      else
        format.html { render action: "new" }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pacientes/1
  # PUT /pacientes/1.json
  def update
    @paciente = Paciente.find(params[:id])

    respond_to do |format|
      if @paciente.update_attributes(params[:paciente])
        format.html { redirect_to @paciente, notice: 'Paciente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente = Paciente.find(params[:id])
    @paciente.destroy

    respond_to do |format|
      format.html { redirect_to pacientes_url }
      format.json { head :no_content }
    end
  end
end

agendaMedica/app/helpers/pacientes_helper.rb
module PacientesHelper
end

agendaMedica/app/views/pacientes/_form.html.erb
<%= form_for(@paciente) do |f| %>
  <% if @paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
      <% @paciente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br />
    <%= f.number_field :idade %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :rg %><br />
    <%= f.text_field :rg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

agendaMedica/app/views/pacientes/edit.html.erb
<h1>Editing paciente</h1>

<%= render 'form' %>

<%= link_to 'Show', @paciente %> |
<%= link_to 'Back', pacientes_path %>

agendaMedica/app/views/pacientes/index.html.erb
<h1>Listing pacientes</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th>Idade</th>
    <th>Endereco</th>
    <th>Rg</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pacientes.each do |paciente| %>
  <tr>
    <td><%= paciente.id %></td>
    <td><%= paciente.nome %></td>
    <td><%= paciente.idade %></td>
    <td><%= paciente.endereco %></td>
    <td><%= paciente.rg %></td>
    <td><%= link_to 'Show', paciente %></td>
    <td><%= link_to 'Edit', edit_paciente_path(paciente) %></td>
    <td><%= link_to 'Destroy', paciente, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paciente', new_paciente_path %>

agendaMedica/app/views/pacientes/new.html.erb
<h1>New paciente</h1>
<% if @paciente.errors.any? %>
	<h2>Erros:</h2>
	<ul>
		<% @paciente.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
		<% end %>r
	</ul>
<% end %>
<%= render 'form' %>

<%= link_to 'Back', pacientes_path %>

agendaMedica/app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @paciente.id %>
</p>

<p>
  <b>Nome:</b>
  <%= @paciente.nome %>
</p>

<p>
  <b>Idade:</b>
  <%= @paciente.idade %>
</p>

<p>
  <b>Endereco:</b>
  <%= @paciente.endereco %>
</p>

<p>
  <b>Rg:</b>
  <%= @paciente.rg %>
</p>


<%= link_to 'Edit', edit_paciente_path(@paciente) %> |
<%= link_to 'Back', pacientes_path %>