agendaMedica/config/routes.rb
AgendaMedica::Application.routes.draw do
  resources :medicos

  resources :convenios

  resources :pacientes

  resources :agendamentos

  get "home/index"









  root :to => 'home#index'


end

agendaMedica/app/models/convenio.rb
class Convenio < ActiveRecord::Base
  attr_accessible :id, :nome
  
  validates :id, :nome, :presence => true 
  validates :id, :numericality => { :only_integer => true }
  validates :id, :uniqueness => { :message => "Campo ID  unico" }
  validates :nome, :length => { :maximum => 100, :message => "nome e no maximo 200 caracteres"}    
end

agendaMedica/app/controllers/convenios_controller.rb
class ConveniosController < ApplicationController
  # GET /convenios
  # GET /convenios.json
  def index
    @convenios = Convenio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @convenios }
    end
  end

  # GET /convenios/1
  # GET /convenios/1.json
  def show
    @convenio = Convenio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @convenio }
    end
  end

  # GET /convenios/new
  # GET /convenios/new.json
  def new
    @convenio = Convenio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @convenio }
    end
  end

  # GET /convenios/1/edit
  def edit
    @convenio = Convenio.find(params[:id])
  end

  # POST /convenios
  # POST /convenios.json
  def create
    @convenio = Convenio.new(params[:convenio])

    respond_to do |format|
      if @convenio.save
        format.html { redirect_to @convenio, notice: 'Convenio was successfully created.' }
        format.json { render json: @convenio, status: :created, location: @convenio }
      else
        format.html { render action: "new" }
        format.json { render json: @convenio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /convenios/1
  # PUT /convenios/1.json
  def update
    @convenio = Convenio.find(params[:id])

    respond_to do |format|
      if @convenio.update_attributes(params[:convenio])
        format.html { redirect_to @convenio, notice: 'Convenio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @convenio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /convenios/1
  # DELETE /convenios/1.json
  def destroy
    @convenio = Convenio.find(params[:id])
    @convenio.destroy

    respond_to do |format|
      format.html { redirect_to convenios_url }
      format.json { head :no_content }
    end
  end
end

agendaMedica/app/helpers/convenios_helper.rb
module ConveniosHelper
end

agendaMedica/app/views/convenios/_form.html.erb
<%= form_for(@convenio) do |f| %>
  <% if @convenio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@convenio.errors.count, "error") %> prohibited this convenio from being saved:</h2>

      <ul>
      <% @convenio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

agendaMedica/app/views/convenios/edit.html.erb
<h1>Editing convenio</h1>

<%= render 'form' %>

<%= link_to 'Show', @convenio %> |
<%= link_to 'Back', convenios_path %>

agendaMedica/app/views/convenios/index.html.erb
<h1>Listing convenios</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @convenios.each do |convenio| %>
  <tr>
    <td><%= convenio.id %></td>
    <td><%= convenio.nome %></td>
    <td><%= link_to 'Show', convenio %></td>
    <td><%= link_to 'Edit', edit_convenio_path(convenio) %></td>
    <td><%= link_to 'Destroy', convenio, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Convenio', new_convenio_path %>

agendaMedica/app/views/convenios/new.html.erb
<h1>New convenio</h1>
<% if @convenio.errors.any? %>
	<h2>Erros:</h2>
	<ul>
		<% @convenio.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
		<% end %>r
	</ul>
<% end %>
<%= render 'form' %>

<%= link_to 'Back', convenios_path %>

agendaMedica/app/views/convenios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @convenio.id %>
</p>

<p>
  <b>Nome:</b>
  <%= @convenio.nome %>
</p>


<%= link_to 'Edit', edit_convenio_path(@convenio) %> |
<%= link_to 'Back', convenios_path %>